### ISSUE TITLE
what's the meaning of this line?

### ISSUE THREAD

**Issue by stkevintan** [CKGrafico/inversify-props#1]
https://github.com/CKGrafico/inversify-props/blob/9d0313987d3364b2833591acffd39195630b2bc0/src/lib/helpers.ts#L28

I copy this line to my file but got a error:
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '(target: object, propertyKey: string | number | symbol) => boolean'.
  No index signature with a parameter of type 'string' was found on type '(target: object, propertyKey: string | number | symbol) => boolean'.ts(7053)
```

**Comment by CKGrafico** [comment]
This line is deleting the property and the next line is creating a new property with the dependency injected into the Class

**Comment by stkevintan** [comment]
@CKGrafico I know you are intend to delete the property and readd it with a custom getter.

However, I think `Reflect.deleteProperty` is a function not an object, it cannot be invoked by  `[key]`

The right way should be: 

```js
Reflect.deleProperty(target, key)
```

Am I right ?

**Comment by CKGrafico** [comment]
Which version of typescript are you using? This is working in all our projects, can you download the examples and test them?

**Comment by CKGrafico** [comment]
check with he new version

**Comment by stkevintan** [comment]
Thx, the ts 3.5 show no error of your form.

**Comment by CKGrafico** [comment]
Yeah! thanks for your patience and sorry for the bug :)
