### ISSUE TITLE
Error with Vue in production.

### ISSUE THREAD

**Issue by nunonux** [CKGrafico/inversify-props#11]
Hello,
I'm having an error when I build my Vue Application. So, when I run my Vue Application in development mode it doesn't throw the error but when I build it to production, I keep having this problem. I don't know why. I have spent hours trying to figure this and googled a lot but could not understand the problem.

Error:
"No matching bindings found for serviceIdentifier: Symbol(IAppConfig)" 

My Code:
```
export class ContainerBuilder {
    build() {
        container.addSingleton<IAppConfig>(AppConfig);
    }
}
//===========
AppConfig.ts

@injectable()
export class AppConfig implements IAppConfig {
    get HostApi() {
        return this.hostApi;
    }
}

export interface IAppConfig {
    readonly HostApi: string | undefined;
}

```

**Comment by CKGrafico** [comment]
Are you uglifying your code? https://github.com/CKGrafico/inversify-props#how-to-configure-uglify-or-terser

**Comment by nunonux** [comment]
No. But it work if you set customIds to in your container and in the inject decorator.

I was checking for the error and I found that if you use vue-cli to scaffold a project  with typescript and babel, it will not emit the decorator metadata. It's because the when compiling the babel plugin with strip out all typescript features.

To reproduce the issue, scaffold a project with vue-cli, set to use typescript and to use babel with it. When you set emitDecoratorMetadata to true and compile it will throw some warnings say something like 'IService was not found in [dir-name]'.

**Comment by CKGrafico** [comment]
That error is usually related to minification and obfuscation of code, is this happening in dev or only in prod?

**Comment by nunonux** [comment]
only on prod. But I setup the uglifying part and it worked. Thanks

**Comment by CKGrafico** [comment]
Was never a problem, was a lack reading the docs :)

> Are you uglifying your code? https://github.com/CKGrafico/inversify-props#how-to-configure-uglify-or-terser

**Comment by bobo-k2** [comment]
Thanks a lot for the quick answer. I am famous for not reading full documentation :)
