### ISSUE TITLE
*bug* IE 11 Not supported :: 

### ISSUE THREAD

**Issue by piyushsh** [CKGrafico/inversify-props#18]
Hi there,

In IE11, we uses polyfills to support `Symbol` (i.e. core-js/es/symbol), now in your codebase I noticed you are checking the type of symbol as below.

![image](https://user-images.githubusercontent.com/10875373/74675799-4742b400-51ac-11ea-93f1-fca389cb8edf.png)

As because of polyfills, this will be treated as `object` type, 'cause of which it will never find the `realCid` and won't resolve the dependancy.

Please look into this.

**Comment by CKGrafico** [comment]
I think this is not happening from 2.0
