### ISSUE TITLE
2.0.1 is not working

### ISSUE THREAD

**Issue by lepicekmichal** [CKGrafico/inversify-props#21]
`Cannot apply @injectable decorator multiple times.`

Even https://github.com/CKGrafico/Frontend-Boilerplates/tree/vue is not working with 2.0.1

**Comment by webnoob** [comment]
I also get this on 2.0.1

Any news on a fix?

**Comment by CKGrafico** [comment]
Did you removed `@injectable`from your code? check the demos maybe is that

**Comment by webnoob** [comment]
I've made no code changes at all. `@injectable` exists where it always has...

**Comment by webnoob** [comment]
Oh wait, we don't need `@injectable` now?

https://github.com/CKGrafico/inversify-props/blob/master/examples/vue/src/app/shared/service1/service1.service.ts

**Comment by CKGrafico** [comment]
@webnoob yes injectable is not necessary anymore, sorry for the porr explanation :( I'll check how to give this info to devs. Suggestions and PRs are accepted to explain this to others

**Comment by webnoob** [comment]
@CKGrafico Perhaps just tag a release in the releases section and add a "Breaking Change" note in there to explain this. It was the first place I looked when upgrading as this seems to be the standard way to explain any changes to users.

**Comment by CKGrafico** [comment]
Yes, you're totally right I'm not maintaining this project as a project that people uses because I don't have a lot of feedback in github (at least no like in my other projects) I can see that there is some people using it, I'll try to improve the docs and releases in the future.

**Comment by webnoob** [comment]
Just an extra thought on this, is it worth removing `injectable` as a named export on the `inversify-props` package as well?

**Comment by CKGrafico** [comment]
You need for 3rd party https://github.com/CKGrafico/Frontend-Boilerplates/blob/phaser/src/app/core/phaser/phaser.injectables.ts
