### ISSUE TITLE
[question]Difference between inversify-props and inversify-inject-decorators

### ISSUE THREAD

**Issue by rdhainaut** [CKGrafico/inversify-props#24]
Hello,

I find your library interessant but I would like know what the differences between this library and the https://github.com/inversify/inversify-inject-decorators library ?

In other words, why develop this new library and not use lazyInject decorator ?

**Comment by CKGrafico** [comment]
Thanks for your question, this project is a wrapper on inversify to simplify some functionalities around components not just to decorate properties. Maybe we can also wrap inversify-inject-decorators in the future I don't know what @remojansen thinks about that :)

**Comment by CKGrafico** [comment]
Closing because @remojansen is not replying :)
