### ISSUE TITLE
Reflect.hasOwnMetadata is not a function

### ISSUE THREAD

**Issue by dTalion** [CKGrafico/inversify-props#3]
injectable.js?719e:7 Uncaught TypeError: Reflect.hasOwnMetadata is not a function

injectable.js?719e:7 Uncaught TypeError: Reflect.hasOwnMetadata is not a function
    at eval (injectable.js?719e:7)
    at Module.__decorate (tslib.es6.js?9ab4:56)

**Comment by CKGrafico** [comment]
Yes in the new version 'reflect-metadata' is a peerdependency, please see the examples :) and read the docs, I will update them to give more information
