### ISSUE TITLE
Issue with 1.4.0

### ISSUE THREAD

**Issue by sbmw** [CKGrafico/inversify-props#4]
Hi, I have some problems on upgrade from 1.3.5 to 1.4.0

I made the upgrade and changed all references to "Inject" (with a capital I) to "inject" as per the updated documentation.

However on run I get:

`Error: @inject called with undefined this could mean that the class undefined has a circular dependency problem. You can use a LazyServiceIdentifer to  overcome this limitation.`

Is this a bug or is there something else I need to change for 1.4.0?  Everything was working perfectly before the upgrade.

I expect this is unrelated, but during build I also now get these warnings from the parceljs bundler, which didn't happen before:

```
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/inversify-props/dist/index.js".
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/inversify-props/dist/index.js".
⚠️  Could not load source file "../../src/lib/helpers.ts" in source map of "../node_modules/inversify-props/dist/lib/helpers.js".
⚠️  Could not load source file "../../src/lib/container.ts" in source map of "../node_modules/inversify-props/dist/lib/container.js".
```

**Comment by sbmw** [comment]
I just cycled back through versions and in fact the issues start in v1.3.6 with https://github.com/CKGrafico/inversify-props/commit/d838d7e37786da051bd95e0f505fb6f7e6ddc4af

I'm using IDs as follows:

```
export const AppDiTypes = {
    MyServiceClient: "MyServiceClient",
}
```

`container.addSingleton<IMyServiceClient>(MyServiceClient, AppDiTypes.MyServiceClient);`

```
@Inject(AppDiTypes.MyServiceClient)
private myServiceClient: IMyServiceClient;
```

Thanks!

**Comment by CKGrafico** [comment]
For the first thing I removed `src` from the package I'll add again sorry.
For the second, can you give me a repo to reproduce it?

**Comment by sbmw** [comment]
No problem: https://github.com/sbmw/propsdemo

The initial package.json is set to use inversify-props@1.3.5

1. npm install -g parcel-bundler
2. npm install
3. npm run build

Result: everything works and you get a greeting message from the injected service/

1. Update to inversify-props@1.4.1
2. npm run build

Result: the error message I listed above.

**Comment by CKGrafico** [comment]
Bug detected, sorry for the bad experience, I'm fixing right now.

PS: If you cant you can use `cid` object instead generate your own ids (if there are no bugs.. xD)

**Comment by sbmw** [comment]
Wow, amazing!

Thanks for such a quick fix and for a very useful package!
