### ISSUE TITLE
Singleton scope doesn't seem to work

### ISSUE THREAD

**Issue by webnoob** [CKGrafico/inversify-props#5]
Hi, 

I've got an Auth Service which I use to track an authenticated user.

When declaring the service like:
```
container.addSingleton<IAuthService>(AuthService)
```

The constructor is called twice on `AuthService` when the service is injected via 

```
@Inject()
private readonly authService!: AuthService
```

However, if I use the root container instead, and bind the module like:

```
container.bind<AuthService>(AuthService).toSelf().inSingletonScope()
```

then inject it like:

```
private readonly authService: AuthService = container.get(AuthService)
```

The `AuthService` constructor is only called once and the data I entered when logging my user in is still present (as the instance isn't recreated).

Am I misunderstanding your singleton implementation or is this a bug?

EDIT: I've just been playing around and it's worth noting, the first time I'm calling the service, I'm doing do via `container.resolve(AuthService)` which might explain why I get a second instance because if I try `container.get(AuthService)` and have I've bound the service using the `container.addSingleton<IAuthService>(AuthService)` method, I get an error saying the AuthService isn't bound.

I guess on that note then, I should be asking - why isn't the service bound when calling `container.get(AuthService)` as I would have expected it to be bound because of `container.addSingleton<IAuthService>(AuthService)`

**Comment by webnoob** [comment]
I've written my own decorator that bypassed your internal ID stuff and it's working so I guess this is where my issue lies:

```ts
export function injectSingleton (type: any): any {
  return function (target: any, targetKey: string, index?: number): any {
    Reflect.deleteProperty(target, targetKey)
    Reflect.defineProperty(target, targetKey, {
      get () {
        return container.get(type)
      },
      set (value) {
        return value
      }
    })
  }
}
```

**Comment by CKGrafico** [comment]
I'll check soon thanks, if you can provide a codesandbox or something reproducing the bug will be easier

**Comment by CKGrafico** [comment]
Hello @webnoob I've created this codesandbox to try to reproduce your bug, my constructor is called once https://codesandbox.io/s/old-frost-dpkcv feel free to modify it to reproduce the issue.
![issue](https://i.imgur.com/aRMOICc.png)

**Comment by dedreira** [comment]
Wow I've just experimented same issue with a Vue app, I injected a dependency (registered as a singleton into a component) but every time I hit the route that redirected to the component, the constructor of the dependency got called...quite annoying... 😠 
At the end I found that the error was that I was not decorating properly my component class, I was doing this:
```typescript
@Component
export default class HelloWorld extends Vue
````
instead of this:
```typescript
@Component({
  
})
export default class HelloWorld extends Vue 
````
Maybe this can help you try to find the issue....if this is really an issue 😸
