### ISSUE TITLE
Injecting into injectable doesn't seem to work

### ISSUE THREAD

**Issue by dazzling-babbage** [CKGrafico/inversify-props#9]
Hi,

I have a client and an injectable service in a Vue project, and I want to inject the client into the service:
```
@injectable()
export class Service {
    @inject(CONTAINER_IDS.Client) private client!: Client
}
```
This in itself should not be an issue since it is done in the vue example https://github.com/CKGrafico/inversify-props/tree/master/examples/vue.
Both client and service are added to the container like so:
```
container.addSingleton<Client>(Client, CONTAINER_IDS.Client)
container.addSingleton<Service>(Service, CONTAINER_IDS.Service)
```
Client is just an empty injectable:
```
@injectable()
export class Client {
}
```
But the main view is not displayed. Neither client nor service are used anywhere else. Firefox gives the following error:
```
TypeError: _container__WEBPACK_IMPORTED_MODULE_3__.default is undefined
```
And  in Chrome: 
```
Uncaught TypeError: Cannot read property 'Client' of undefined
```
I have uploaded the sample project here: https://github.com/dazzling-babbage/inversify-issue
The sample project is extracted from a real project, which is why there are so many dependencies etc. 

You can use `npm run serve` to run it. It should just display the text `YAY!`, but displays a white page instead due to the errors above. If you comment out `container.addSingleton<Service>(Service, CONTAINER_IDS.Service)` in `container.ts` it runs fine, the same if you comment out `@inject(CONTAINER_IDS.Client) private client!: Client` in `service.ts`.

I am really at a loss as to what I am doing wrong. It would be great if you could look into this.

Thanks a lot

**Comment by CKGrafico** [comment]
Hello,

I've checked your code,

The problem is that CONTAINER_IDS is undefined, this could be because in your `main.ts`you're importing app.vue before container and when you try to inject your service your constants does not exist, I've made a PR to you with some suggestions (trying to respect your workflow and structure).

https://github.com/dazzling-babbage/inversify-issue/pull/4
